### ISSUE TITLE
Display none not working properly on 38em screen

### ISSUE THREAD

**Issue by baut0015** [baut0015/hide-show-responsively#1]
I added the display:none for the diplodocus image however the browser is still acting as if its there but hidden. Since the remaining images aren't properly using flexbox (whenever I toggle off the inline flex it acts as if theres no image.) Even when i change the property to inline-block the same thing happens.
<img width="1391" alt="diploscrewyou" src="https://user-images.githubusercontent.com/55094055/68618335-15c49900-0497-11ea-9f9a-371da70da341.png">

I don't get what's wrong.  @thomasjbradley

**Comment by thomasjbradley** [comment]
It’s not the `img` we want to hide but the `div` it’s inside.

**Comment by baut0015** [comment]
I tried changing the class to make it easier and it worked that way but I see youuuuu, forcing us to use the child selectors. Thanks for the feedback though it worked! :)
